Yii/models/Categories.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "categories".
 *
 * @property int $id
 * @property string $category
 */
class Categories extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'categories';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category' => 'Category',
        ];
    }
}

Yii/models/Image.php
<?php

namespace app\models;
use Yii;
use yii\base\Model;
use yii\web\UploadedFile;

class Image extends Model {

    public static function uploadImage(UploadedFile $file) {
        echo $fileName = strtolower(md5(uniqid($file->baseName))).'.'."$file->extension";
        $file->saveAs(Yii::getAlias('@web').'uploads/'.$fileName);
        return $fileName;
    }

}

Yii/models/News.php
<?php

namespace app\models;

class News extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['title', 'description', 'content'], 'required'],
            [['title', 'description', 'content'], 'string'],
            [['date'], 'date', 'format' => 'php:Y-m-d H:i:s', 'message' => 'Time format looks like this: 2000-12-31 23:59:59 or leave it blank for the present time'],
            [['date'], 'default', 'value' => date('Y-m-d H:i:s')],
            [['title'], 'string', 'max' => 255],
            [['img'], 'image', 'extensions' => 'png, jpg', 'message' => 'sdad'],
            [['category_id'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'content' => 'Content',
            'date' => 'Date',
            'img' => 'Image',
            'likes' => 'Likes',
            'category_id' => 'Category ID',
        ];
    }

    public function setImage($img) {
        $this->img = $img;
    }

}

Yii/models/NewsSearch.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;
use app\models\News;

/**
 * NewsSearch represents the model behind the search form of `app\models\News`.
 */
class NewsSearch extends News {

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['id', 'likes'], 'integer'],
            [['title', 'description', 'content', 'date', 'img', 'category_id'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function scenarios() {
        // bypass scenarios() implementation in the parent class
        return Model::scenarios();
    }

    public function search() {
        $query = News::find();
        if (Yii::$app->request->get('sort') == 'date' || Yii::$app->request->get('sort') == NULL) {
            $query = $query->orderBy('date DESC');
        } else {
            $query = $query->orderBy('likes DESC');
        }
        if (!empty(Yii::$app->request->get('category'))) {
            $query = $query->where('category_id=:category_id', ['category_id' => Yii::$app->request->get('category')]);
        }
        $news = $query->all();
        return $news;
    }

}

Yii/controllers/MainController.php
<?php

namespace app\controllers;

class MainController extends \yii\web\Controller {

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionError() {
        return $this->render('error');
    }

}

Yii/controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\News;
use app\models\Categories;
use app\models\NewsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use app\models\Image;
use yii\helpers\ArrayHelper;

class NewsController extends Controller {

    public function actionIndex() {
        $searchModel = new NewsSearch();
        $news = $searchModel->search();

        return $this->render('index', [
                    'news' => $news, 'categories' => $this->getCategoryList(),
        ]);
    }

    public function actionView($id) {
        if (Yii::$app->request->get('like') == 'yes') {
            $news = News::find()->where('id=:id', ['id' => $id])->one();
            $likes = $news['likes'] + 1;
            $news = News::updateAll(['likes' => "$likes"], ['id' => "$id"]);
        }
        return $this->render('view', [
                    'info' => $this->findNews($id),
        ]);
    }

    public function actionCreate() {

        $model = new News();

        if ($model->load(Yii::$app->request->post())) {
            $file = UploadedFile::getInstance($model, 'img');
            $img = Image::uploadImage($file);
            $model->setImage($img);
            var_dump($model->attributes);
            $model->save();
            return $this->redirect(['view', 'id' => $model->id]);
        }
        return $this->render('create', [
                    'model' => $model, 'items' => $this->getCategoryList(),
        ]);
    }

    protected function findNews($id) {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function findCategories($id) {
        if (($categories = Categories::findOne($id)) !== null) {
            return $categories;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }

    protected function getCategoryList() {
        $categories = Categories::find()->all();
        $items = ArrayHelper::map($categories, 'id', 'category');
        return $items;
    }

}

Yii/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"">
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-left'],
        'items' => [
            ['label' => 'Main page', 'url' => ['/main/index']],
            ['label' => 'News', 'url' => ['/news/index']],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

Yii/views/main/error.php
<?php
/* @var $this yii\web\View */
?>
<h1>Error!</h1>

Yii/views/main/index.php
<?php
/* @var $this yii\web\View */
?>
<h1>/main/index</h1>

<p>
    You may change the content of this page by modifying
    the file <code><?= __FILE__; ?></code>.
</p>

Yii/views/news/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<div class="news-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'content')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'img')->fileInput() ?>

    <?= $form->field($model, 'date')->textInput() ?>
    
    <?= $form->field($model, 'category_id')->dropDownList($items) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

Yii/views/news/create.php
<?php

use yii\helpers\Html;

$this->title = 'Add news';
?>
<div class="news-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?=
    $this->render('_form', [
        'model' => $model, 'items' => $items
    ])
    ?>

</div>

Yii/views/news/index.php
<?php

use yii\helpers\Html;

$this->title = 'News';
?>

<h1>News</h1> 
<?= Html::a('Add news', ['news/create'], ['class' => 'btn btn-primary', 'role' => 'button']) ?>

<?= Html::beginForm(['', 'id' => $id], 'get') ?>
<span>Sort by 
    <?= Html::dropDownList('sort', '', ['likes' => 'likes', 'date' => 'date'], ['prompt' => '']) ?>
    Category
    <?= Html::dropDownList('category', '', $categories, ['prompt' => '']) ?>
    <?= Html::submitButton('ok', ['class' => 'submit btn btn-secondary btn-sm']) ?>
</span>
<?= Html::endForm() ?>
<?php
if (count($news) == 0) {
    echo '<h3>Such news not found</h3>';
} else {
    foreach ($news as $new):
        ?>

        <h3><?= Html::a(Html::encode("{$new->title}"), ['news/view', 'id' => "$new->id"]) ?></h3>
        <?= Html::img(Html::encode("$GLOBALS[HTTP_HOST]/uploads/{$new->img}"), ['width' => '360px']) ?><br>
        <?= Html::encode("{$new->description}") ?>
        <?= Html::a('Read more...', ['news/view', 'id' => "$new->id"]) ?>
        <br>
        <?php
        if ($new->likes != NULL) {
            echo '<i class="fa fa-thumbs-up" aria-hidden="true"></i>';
            echo Html::encode("{$new->likes}");
        }
        ?>
        <i class="fa fa-clock-o" aria-hidden="true"></i>
        <?= Html::encode(date('H:i', strtotime("$new->date"))) ?> 
        <i class="fa fa-calendar" aria-hidden="true"></i> 
        <?= Html::encode(date('d.m.Y ', strtotime("$new->date"))) ?> 

    <?php endforeach;
} ?>

Yii/views/news/view.php
<?php

use yii\helpers\Html;

$this->title = Html::encode("{$info->title}");
?>

<h2>"<?= $info->title ?>"</h2>
<?= Html::img(Html::encode("$GLOBALS[HTTP_HOST]/uploads/{$info->img}"), ['width' => '50%', 'style' => 'float:left']) ?>
<?= Html::encode("{$info->content}"); ?>
<br>
<?php
if ($info->likes != NULL) {
    echo '<i class="fa fa-thumbs-up" aria-hidden="true"></i> ';
    echo Html::encode("{$info->likes}");
}
?>
<i class = "fa fa-clock-o" aria-hidden = "true"></i> 
<?= Html::encode(date('H:i', strtotime("$info->date"))) ?>
<i class = "fa fa-calendar" aria-hidden = "true"></i>
<?= Html::encode(date('d.m.Y ', strtotime("$info->date"))) ?>
<?= Html::beginForm(['', 'id' => "$info->id", 'like' => 'yes'], 'get') ?>
<?= Html::submitButton('I like it!', ['class' => 'btn btn-success']) ?>
<?= Html::endForm() ?>